# High-level labels based on repo structure. Labels are created on first use (issues: write).

rules:
  - changed-files:
      - any-glob-to-any-file: "packages/tff-core/src/tff/core/rules/**"

checks:
  - changed-files:
      - any-glob-to-any-file: "packages/tff-core/src/tff/core/checks/**"

core:
  - all:
      - changed-files:
          - any-glob-to-any-file: "packages/tff-core/src/tff/core/**"
      - changed-files:
          - all-globs-to-all-files: "!packages/tff-core/src/tff/core/rules/**"
      - changed-files:
          - all-globs-to-all-files: "!packages/tff-core/src/tff/core/checks/**"

dbt:
  - changed-files:
      - any-glob-to-any-file: "packages/tff-dbt/**"

sqlmesh:
  - changed-files:
      - any-glob-to-any-file:
          - "packages/tff-sqlmesh/**"
          - "packages/sqlmesh-ff/**"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "**/tests/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

docs:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pyproject.toml"
          - "**/uv.lock"
