"""Duplicate CTEs / Connascence of Algorithm check."""

from __future__ import annotations

import hashlib
import logging
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor
from typing import TYPE_CHECKING, Any

import sqlglot.expressions as exp

from tff.core.parallel import get_max_workers
from tff.core.report import LintFinding
from tff.core.utils.paths import get_layer_from_path, model_path_relative

if TYPE_CHECKING:
    from tff.core.config import FitnessFunctionsConfig
    from tff.core.model import ModelRepresentation

logger = logging.getLogger(__name__)


def is_complex_cte(cte_query: exp.Expression, min_nodes: int) -> bool:
    """Determine if a CTE query meets structural complexity heuristics."""
    # Heuristic 1: Check node count
    node_count = sum(1 for _ in cte_query.walk())
    if node_count < min_nodes:
        return False

    # Heuristic 2: Check structural complexity (Join, Where, Group/Having, Window, Case/If)
    has_complex_structure = any(
        cte_query.find(cls) is not None
        for cls in (exp.Join, exp.Where, exp.Group, exp.Having, exp.Window, exp.Case, exp.If)
    )
    return has_complex_structure


def _extract_paren_content(sql: str, open_paren_idx: int) -> str | None:
    """Extract content inside balanced parentheses starting at open_paren_idx."""
    n = len(sql)
    depth = 0
    in_str = None
    i = open_paren_idx
    while i < n:
        ch = sql[i]
        if in_str:
            if ch == in_str:
                if i + 1 < n and sql[i + 1] == in_str:
                    i += 2
                    continue
                in_str = None
            elif ch == "\\" and i + 1 < n:
                i += 2
                continue
            i += 1
            continue

        # Single-line comment --
        if ch == "-" and i + 1 < n and sql[i + 1] == "-":
            i += 2
            while i < n and sql[i] not in ("\r", "\n"):
                i += 1
            continue

        # Block comment /* ... */
        if ch == "/" and i + 1 < n and sql[i + 1] == "*":
            i += 2
            while i < n and not (sql[i - 1] == "*" and sql[i] == "/"):
                i += 1
            i += 1
            continue

        if ch in ("'", '"', "`"):
            in_str = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return sql[open_paren_idx + 1 : i]
        i += 1
    return None


def is_cte_produced_by_macro(
    cte_name: str,
    cte_query: exp.Expression,
    raw_sql: str | None,
    dialect: str,
    min_ast_nodes: int,
) -> bool:
    """Determine if a complex CTE's transformation logic originated from a macro.

    Returns True if the CTE was generated by a macro call (e.g. {{ macro() }},
    @macro(), or ${macro()}) rather than written directly in the raw model source.
    """
    if not raw_sql or not raw_sql.strip():
        return False

    import re

    # Check for macro syntax indicators across engines:
    # Jinja: {{ ... }} or {% ... %}
    # SQLMesh: @macro(...) or @macro
    # Dataform: ${ ... }
    has_macro_syntax = (
        bool(re.search(r"\{\{.*?\}\}|\{%.*?%\}", raw_sql, re.DOTALL))
        or bool(re.search(r"@\w+(?:\s*\(.*?\))?", raw_sql))
        or bool(re.search(r"\$\{.*?\}", raw_sql, re.DOTALL))
    )
    if not has_macro_syntax:
        return False

    # Check if the CTE is defined with `cte_name AS (` in raw_sql.
    # If the CTE name doesn't appear as a CTE definition in raw_sql,
    # but the model uses macros, then the whole CTE was emitted by a macro!
    cte_def_pattern = re.compile(rf"\b{re.escape(cte_name)}\b\s+AS\s*\(", re.IGNORECASE)
    match = cte_def_pattern.search(raw_sql)
    if not match:
        return True

    # The CTE name is present in raw_sql (e.g. `my_cte AS (...)`).
    # Inspect the body inside the CTE definition in raw_sql.
    open_paren_idx = match.end() - 1
    raw_cte_body = _extract_paren_content(raw_sql, open_paren_idx)
    if raw_cte_body is None:
        return False

    # Check if the CTE body contains a macro call
    body_has_macro = (
        bool(re.search(r"\{\{.*?\}\}|\{%.*?%\}", raw_cte_body, re.DOTALL))
        or bool(re.search(r"@\w+(?:\s*\(.*?\))?", raw_cte_body))
        or bool(re.search(r"\$\{.*?\}", raw_cte_body, re.DOTALL))
    )
    if not body_has_macro:
        return False

    # Clean the raw CTE body of Jinja/SQLMesh/Dataform syntax to see if
    # the complex transformation logic was written directly in the raw SQL.
    from tff.core.parallel import _clean_sql_for_model

    cleaned_body = _clean_sql_for_model(raw_cte_body)

    from tff.core.ast_cache import parse_sql_with_cache

    parsed_body = parse_sql_with_cache(cleaned_body, dialect=dialect)
    if parsed_body is None:
        # If it cannot parse when macros are replaced by dummy identifiers,
        # the SQL logic is inside the macro.
        return True

    # If the cleaned raw CTE body does not meet the complex CTE heuristic,
    # then the complex transformation logic came from expanding the macro!
    if not is_complex_cte(parsed_body, min_ast_nodes):
        return True

    return False


def extract_model_cte_fingerprints(
    task: tuple[Any, ...],
) -> list[tuple[str, dict]]:
    """Extract complex CTE fingerprints for a single model (worker-safe)."""
    model_name = task[0]
    model_path = task[1]
    dialect = task[2]
    ast_or_sql = task[3]
    min_ast_nodes = task[4]
    raw_sql = task[5] if len(task) > 5 else None
    ignore_macros = task[6] if len(task) > 6 else True

    parsed: exp.Expression | None = None
    if isinstance(ast_or_sql, exp.Expression):
        parsed = ast_or_sql
    elif isinstance(ast_or_sql, str) and ast_or_sql.strip():
        from tff.core.ast_cache import parse_sql_with_cache
        from tff.core.parallel import _clean_sql_for_model

        cleaned = _clean_sql_for_model(ast_or_sql)
        parsed = parse_sql_with_cache(cleaned, dialect=dialect)

    if parsed is None:
        return []

    results: list[tuple[str, dict]] = []
    for cte in parsed.find_all(exp.CTE):
        cte_name = cte.alias
        cte_query = cte.this

        if not is_complex_cte(cte_query, min_ast_nodes):
            continue

        canonical_sql = cte_query.sql(dialect=dialect, pretty=False)
        h = hashlib.sha256(canonical_sql.encode("utf-8")).hexdigest()

        is_macro = False
        if ignore_macros and raw_sql:
            is_macro = is_cte_produced_by_macro(
                cte_name,
                cte_query,
                raw_sql,
                dialect,
                min_ast_nodes,
            )

        results.append((
            h,
            {
                "model": model_name,
                "path": model_path,
                "cte_name": cte_name,
                "canonical_sql": canonical_sql,
                "from_macro": is_macro,
            },
        ))
    return results


def collect_duplicate_cte_findings(
    models: dict[str, ModelRepresentation],
    config: FitnessFunctionsConfig,
    max_workers: int | None = None,
) -> list[LintFinding]:
    """Identify duplicate complex CTE transformation logic across models in parallel."""
    rule_config = config.checks.duplicate_ctes
    if not rule_config.enabled:
        return []

    ignore_macros = getattr(rule_config, "ignore_macros", True)

    # Prepare fingerprint extraction tasks for eligible models
    tasks: list[tuple[str, str, str, exp.Expression | str | None, int, str | None, bool]] = []
    for model in models.values():
        if model.is_external or model.is_symbolic:
            continue

        layer = get_layer_from_path(model.path, layer_order=config.layers.order)
        if not rule_config.should_run(layer):
            continue

        raw_or_parsed: exp.Expression | str | None = (
            model.expression if model.expression is not None else model.get_sql()
        )
        raw_sql: str | None = model.get_raw_sql() if ignore_macros else None

        tasks.append((
            model.name,
            model.path,
            model.dialect,
            raw_or_parsed,
            rule_config.min_ast_nodes,
            raw_sql,
            ignore_macros,
        ))

    fingerprints: dict[str, list[dict]] = defaultdict(list)

    if not tasks:
        return []

    workers = get_max_workers(config=config, override=max_workers)
    if workers <= 1 or len(tasks) <= 2:
        for task in tasks:
            for h, occ in extract_model_cte_fingerprints(task):
                fingerprints[h].append(occ)
    else:
        try:
            pool_size = min(workers, len(tasks))
            with ProcessPoolExecutor(max_workers=pool_size) as executor:
                chunksize = max(1, len(tasks) // (pool_size * 4))
                for model_results in executor.map(extract_model_cte_fingerprints, tasks, chunksize=chunksize):
                    for h, occ in model_results:
                        fingerprints[h].append(occ)
        except Exception as exc:
            logger.debug(
                "ProcessPoolExecutor encountered an issue in duplicate_ctes (%s), falling back to sequential",
                exc,
            )
            for task in tasks:
                for h, occ in extract_model_cte_fingerprints(task):
                    fingerprints[h].append(occ)

    findings: list[LintFinding] = []
    # Identify fingerprints that have occurrences across multiple models or multiple times
    for occurrences in fingerprints.values():
        if len(occurrences) > 1:
            macro_count = sum(1 for o in occurrences if o.get("from_macro"))
            # If all occurrences were produced by a macro, skip (centrally managed in macro)
            if macro_count == len(occurrences):
                continue

            # If some occurrences came from a macro, only flag models that duplicated manually
            if macro_count > 0:
                violating_occurrences = [o for o in occurrences if not o.get("from_macro")]
            else:
                violating_occurrences = occurrences

            for occ in violating_occurrences:
                other_occs = [
                    f"model '{o['model']}' (CTE '{o['cte_name']}')"
                    for o in occurrences
                    if o is not occ
                ]
                others_str = (
                    ", and ".join(other_occs)
                    if len(other_occs) <= 2
                    else ", ".join(other_occs[:-1]) + f", and {other_occs[-1]}"
                )

                # Format severity type: warning or error
                severity_type = "error" if rule_config.severity == "error" else "warning"

                message = (
                    f"CTE '{occ['cte_name']}' has duplicate transformation logic with {others_str}. "
                    "This indicates Connascence of Algorithm (CoA) and should be refactored into a shared upstream model or macro."
                )

                findings.append(
                    LintFinding(
                        check="duplicate_ctes",
                        severity=severity_type,
                        model=occ["model"],
                        path=model_path_relative(occ),
                        message=message,
                    )
                )

    return findings
